{% set name = "libev" %}
{% set version = "4.25" %}
{% set sha256 = "78757e1c27778d2f3795251d9fe09715d51ce0422416da4abb34af3929c02589" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: http://dist.schmorp.de/libev/Attic/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 1000
  skip: true  # [win]

requirements:
  build:
    - libtool
    - {{ compiler('c') }}
  host:

test:
  commands:
    # Check for headers.
    - test -f "${PREFIX}/include/ev.h"
    - test -f "${PREFIX}/include/ev++.h"
    - test -f "${PREFIX}/include/event.h"

    # Check for libraries.
    {% set libs = [
        "libev",
    ] %}

    {% for each_lib in libs %}
    - test -f "${PREFIX}/lib/{{ each_lib }}.a"
    - test -f "${PREFIX}/lib/{{ each_lib }}.dylib"         # [osx]
    - test -f "${PREFIX}/lib/{{ each_lib }}.so"            # [linux]
    {% endfor %}


about:
  home: http://software.schmorp.de/pkg/libev.html
  license: BSD-2-Clause
  license_family: BSD
  license_file: LICENSE
  summary: A full-featured and high-performance event loop that is loosely modeled after libevent, but without its limitations and bugs.

extra:
  recipe-maintainers:
    - petercable
    - carlodri
