appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
compiler_stack: comp7
max_py_ver: '37'
max_r_ver: '35'
travis:
  secure: {BINSTAR_TOKEN: z9LyKxABJjq+xKSw7keTm54G6DZIUo9635EVLFac/IXsndbrkOUGBvdMglxzjp9Qcpq8Kfxdj67G7Ikj6MbrrRCW6xPfIhm+KUIz9vQYU8pTaBxZfRkgzWq0JHd6ow03MzAcnxIZsvi5Hjdp6adSdOu0hMaOMuB/U2xOfIldM9DiR6kT/coUdn0Ar6TmkWyHAPhntELrSXQfrtf9LctvxgI5xlEGR2SIwGqeTIJqcl7Qml4iuI1NIOlctGnH9O71T3slzBLXPxtWIM7h4r2mA5C1duinpNKZsMDb0+iapnH4P9vDjC+UQFfCmGV8nnDMBgnWAiAMmGnZNgO4fp9mxgJcVKSomHTdM6oFYoUEAT4RoMp83FsLZ88S3QuHTrvh4jZNthgFFobLzE9pj6kbj8hC+j5ktUIcJ35a7njWonD2fqou8+JSujxSqCY+4CfeVY/0XZ6uzMTp3xHIAw/n2moBGOfI8WsLg2c6O0M5lz/8H4uETtkPCw6CrG8CC+oK6l8mo6HGq/luUfJnkrpJN3SUupDfYbFSpBvzEDyr86xAGu7ehzoe232vsAIX2dJHfD12b57LrvH7QCaV8FKdeG5z3PxUg2Z+j12UJF+FybeM2XXYtYFPRGMf61uPMQ01zxojMlmMoNHmT58+Y5TlKT5bZAU7ennbe3xX/wLvj/0=}
